kind: Service
apiVersion: v1
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50051
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: service
        image: web
        ports:
        - containerPort: 50051
        env:
          - name: PORT
            value: "50051"
          