apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
      - name: service
        env:
          - name: DEBUG
            value: "true"
          - name: FILMS_URL
            value: "films:80"